name: Terraform Deployment

on:
  push:
    branches:
      - master  # This triggers the workflow whenever you push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs the job on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the code from your repository

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # This sets up Terraform on the runner

    - name: Terraform Init
      run: terraform init  # Initializes Terraform in your project

    - name: Terraform Apply
      run: terraform apply -auto-approve  # Applies the Terraform configuration
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Uses your AWS Access Key from secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Uses your AWS Secret Key from secrets
        AWS_REGION: ${{ secrets.AWS_REGION }}  # Uses the AWS Region from secrets
